### ISSUE TITLE
Bot are lagging

### ISSUE THREAD

**Issue by jrgryph** [playerbot/mangos#1]
After combat, the bots don't move for 30-60 seconds.

**Comment by blueboy** [comment]
Hi,

Thanks for the feedback. This might seem like a silly question, but are you using the code from this repo? If so, could you try the code currently under test on the blueboy 'new-ai' branch ( https://github.com/blueboy/portal/tree/new-ai ) and see how it compares. 

Thanks

**Comment by jrgryph** [comment]
Yes I am using this: git clone git://github.com/playerbot/mangos.git.  I will try the new-ai branch and let you know.  Thanks for the help :)

**Comment by jrgryph** [comment]
Hey Blueboy,

Tried the new-ai branch and it works perfectly.  Thanks!
